databaseChangeLog:
  - changeSet:
      id: 0
      author: victor hugo
      changes:
        - createTable:
            tableName: aluno
            columns:
              - column:
                  name: uuid
                  type: varchar(255)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: primeiroNome
                  type: varchar(50)
              - column:
                  name: ultimoNome
                  type: varchar(50)
              - column:
                  name: rua
                  type: varchar(50)
              - column:
                  name: cidade
                  type: varchar(50)
              - column:
                  name: estado
                  type: varchar(50)
              - column:
                  name: cep
                  type: int(50)
              - column:
                  name: email
                  type: varchar(50)
              - column:
                  name: username
                  type: varchar(50)
              - column:
                  name: senha
                  type: varchar(255)
              - column:
                  name: xp
                  type: int
              - column:
                  name: ehPremium
                  type: boolean
        - createTable:
            tableName: professor
            columns:
              - column:
                  name: uuid
                  type: varchar(255)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: primeiroNome
                  type: varchar(50)
              - column:
                  name: ultimoNome
                  type: varchar(50)
              - column:
                  name: rua
                  type: varchar(50)
              - column:
                  name: cidade
                  type: varchar(50)
              - column:
                  name: estado
                  type: varchar(50)
              - column:
                  name: cep
                  type: int(50)
              - column:
                  name: email
                  type: varchar(50)
              - column:
                  name: username
                  type: varchar(50)
              - column:
                  name: senha
                  type: varchar(255)
        - createTable:
            tableName: admin
            columns:
              - column:
                  name: uuid
                  type: varchar(255)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: varchar(50)
              - column:
                  name: email
                  type: varchar(50)
              - column:
                  name: senha
                  type: varchar(255)
        - createTable:
            tableName: post
            columns:
              - column:
                  name: id
                  type: int(11)
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: uuidProfessor
                  type: varchar(255)
                  references: professor(uuid)
                  constraints:
                    nullable: false
              - column:
                  name: data
                  type: date
              - column:
                  name: titulo
                  type: varchar(50)
              - column:
                  name: texto
                  type: longtext
              - column:
                  name: img
                  type: varchar(255)
        - createTable:
            tableName: licao
            columns:
              - column:
                  name: id
                  type: int(11)
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: uuidProfessor
                  type: varchar(255)
                  references: professor(uuid)
                  constraints:
                    nullable: false
              - column:
                  name: titulo
                  type: varchar(50)
              - column:
                  name: descricao
                  type: longtext
              - column:
                  name: nivel
                  type: int(11)
              - column:
                  name: recompensa
                  type: int(11)
              - column:
                  name: tag
                  type: varchar(50)
              - column:
                  name: desafio
                  type: varchar(50)
              - column:
                  name: video
                  type: varchar(255)
              - column:
                  name: ehPremium
                  type: boolean
        - createTable:
            tableName: chat
            columns:
              - column:
                  name: id
                  type: int(11)
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: uuid
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: uuidProfessor
                  type: varchar(255)
                  references: professor(uuid)
                  constraints:
                    nullable: false
              - column:
                  name: uuidAluno
                  type: varchar(255)
                  references: aluno(uuid)
                  constraints:
                    nullable: false
              - column:
                  name: idLicao
                  type: int(11)
                  references: licao(id)
                  constraints:
                    nullable: false
              - column:
                  name: data
                  type: date
              - column:
                  name: msg
                  type: varchar(50)
              - column:
                  name: remetente
                  type: varchar(50)
