version: '3'
services:
  tensorflow:
    build: ../dockerfiles/tensorflow
    image: yogar-ml
    container_name: yogar-ml
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - "../dockerfiles/tensorflow/app:/app"
