version: '3'
services:
  api-test:
    build: ../dockerfiles/node-dev/
    image: yogar-nodejs-test
    container_name: yogar-api-test
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql-server
      - DB_PASSWORD=y0g4rp4ss
      - LIQUIBASE=yogar-liquibase-test
      - TEST=test
    volumes:
      - ../../:/app
    links:
      - mysql-test:mysql-server
    depends_on:
      - liquibase-test

  liquibase-test:
    build: ../dockerfiles/liquibase
    image: yogar-liquibase
    container_name: yogar-liquibase-test
    environment:
      - DB_PASSWORD=y0g4rp4ss
      - DB_HOST=mysql-test
    volumes:
      - ../dockerfiles/liquibase/changelog:/changelog
    links:
      - mysql-test:mysql-server
    depends_on:
      - mysql-test

  mysql-test:
    build: ../dockerfiles/mysql
    image: yogar-mysql
    container_name: yogar-db-test
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=y0g4rp4ss
      - MYSQL_DATABASE=yogar

  tensorflow:
    build: ../dockerfiles/tensorflow
    image: yogar-ml
    container_name: yogar-ml
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - "../dockerfiles/tensorflow/app:/app"
