version: '3'
services:
  api-test:
    build: ../dockerfiles/node-dev/
    image: yogar-nodejs-test
    container_name: yogar-api-test
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql-server
      - DB_PASSWORD=y0g4rp4ss
      - TEST=test
    volumes:
      - ../../:/app
    links:
      - mysql:mysql-server
    depends_on:
      - mysql

  liquibase:
    build: ../dockerfiles/liquibase
    image: yogar-liquibase
    container_name: uea-liquibase
    environment:
      - DB_PASSWORD=y0g4rp4ss
      - DB_HOST=mysql-test
    links:
      - mysql:mysql-server
    depends_on:
      - mysql

  mysql:
    build: ../dockerfiles/mysql
    image: yogar-mysql-test
    container_name: yogar-db-test
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=y0g4rp4ss
      - MYSQL_DATABASE=yogar
    volumes:
      - yogar-test:/var/lib/mysql

volumes:
  yogar-test:

networks:
  foo:    
